language: python
python:
  - "2.7"

install:
  - "pip install ."
  - "pip install -r test-requirements.txt"

# command to run tests
script:
  - |
    if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
      pytest
    else
      pytest -m hermetic
    fi

# Publish the Docker image to the infra AWS registry
before_deploy:
  - pip install --user awscli; export PATH=$PATH:$HOME/.local/bin
deploy:
  provider: script
  script: sh ci/publish-docker.sh
  on:
    branch: master
